language: php

git:
  submodules: false

cache:
  directories:
  - vendor
  - plugins
  - node_modules

env:
  global: APP_ENV=testing

services: mysql

install: composer install

before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- php artisan key:random
- php artisan salt:random

script: ./vendor/bin/phpunit

matrix:
  include:
  - php: 7.1
    script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml
    after_success:
    - bash <(curl -s https://codecov.io/bash) -cF php
  - php: 7.2
  - node_js: 8
    language: node_js
    install: yarn
    before_script:
    - echo "Testing JavaScript Code" > /dev/null
    script:
    - yarn run lint
    - yarn test:coverage
    after_success:
    - yarn run codecov
